# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d9c2c822a56f25ec1a2c4214bd7303bad8e425859302ced2648893150b833d1474a8e9fce06d9f07260fedd40cd2051b3bb34231c252e37d500c8d5f036d27

test:
  secret_key_base: c2ba46c38052ae7112b0581422dd75ca90ef3bfec305b586120236796a47fdc1e1855491e1445070274d9d86f06467db3c57f81299a04034ec6e542594cd2052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
